### ISSUE TITLE
Morph code base

### ISSUE THREAD

**Issue by IanTeo** [CS2103AUG2016-W14-C4/main#14]

**Comment by IanTeo** [comment]
Guys please pull this. I hope it works.

**Comment by IanTeo** [comment]
I have not changed all the names.. so someone change it.
Please becareful when changing it. I changed some and it broke. Haha.
That's why I merge it first before changing the names

**Comment by l0g1cal** [comment]
Shit I am doing this also
Lol

**Comment by IanTeo** [comment]
Oh dear.. see la never make issue! Sorry I also didn't create.. cause i scared i mess up lol. So I was just playing around and it worked.. so I went ahead and merge

**Comment by IanTeo** [comment]
Sorry!!

**Comment by l0g1cal** [comment]
Lol it is fine. I will merge your changes. I basically just renamed stuff. Shouldn't create too much issue as I think we renamed similarly

**Comment by IanTeo** [comment]
Hopefully this is the last "collision" 👍

**Comment by IanTeo** [comment]
Once u done with the renaming close the issue ok?

**Comment by l0g1cal** [comment]
Ok I am done resolving the conflicts. I definitely missed out a few 'renaming' stuff. So I won't close this just yet

**Comment by l0g1cal** [comment]
I guess now that renaming is almost done, we will focus on just implementing floating tasks by Wednesday

**Comment by IanTeo** [comment]
Let's not change the issue name. Instead we close this issue and create a new one.
