### ISSUE TITLE
Tags not transfered after editing

### ISSUE THREAD

**Issue by yamidark** [CS2103AUG2016-W14-C4/main#216]
How do we want to handle tags after editing? Add on or replace?

**Comment by IanTeo** [comment]
We should keep all tags if no tags are specified. 
I guess when tags are specified we will replace all tags with the specified tags..

**Comment by IanTeo** [comment]
But the again, if we have the time, I would like our edit command to be more robust.. like they can specify 
"-" or something if they wanna delete. But it is hard to implement it so that it is not clunky to use..
