### ISSUE TITLE
Fix About Us formatting

### ISSUE THREAD

**Issue by l0g1cal** [CS2103AUG2016-W14-C4/main#5]

**Comment by IanTeo** [comment]
What is wrong with the formatting?

**Comment by l0g1cal** [comment]
Lol there are spaces between roles and responsibilities for some and no spaces for some. I don't seem to know how to fix.

**Comment by IanTeo** [comment]
If you are satisfied with the "fix" just close the issue.

**Comment by l0g1cal** [comment]
Ah yes thanks!
