### ISSUE TITLE
Edit user guide Features with "command format"

### ISSUE THREAD

**Issue by IanTeo** [CS2103AUG2016-W14-C4/main#7]
Command format should contain the details that are currently contained in Create a new task

**Comment by IanTeo** [comment]
What do you guys think? 
Should we put in under "Command Format" or "Create a new task"?
Because the details under "Create a new task" are relevant to all other commands..
But at the same time, putting it there feels like forward referencing

**Comment by JJ-Rachel** [comment]
I'm thinking maybe it can be a call out under create a new task? ^^
