### ISSUE TITLE
Update AboutUs.md page

### ISSUE THREAD

**Issue by IanTeo** [CS2103AUG2016-W14-C4/main#8]
From CS2103T module website:
Update the AboutUs.md page. In particular, indicate which member is in charge of which component (i.e. UI, Logic, Storage, etc.).

**Comment by IanTeo** [comment]
If everyone is OK with the roles Rachel has distributed, I can close this issue.
Comment if you are ok/not ok with it

**Comment by IanTeo** [comment]
I am OK with doing the storage

**Comment by yamidark** [comment]
im ok wif logic

**Comment by l0g1cal** [comment]
I am ok with UI. I guess this can be closed already. Rachel, you can just merge this commit straight to master

**Comment by IanTeo** [comment]
Issue not resolved. Did not merge with master
